export 'src/passwort.dart';
export 'src/name.dart';
export 'src/email.dart';
export 'package:formz/formz.dart';


//DIESE FILES DIENEN DAZU EINE FEHLERMELDUNG DARZUSTELLEN

//BEI DER EMAIL IST ES SO DASS SIE EIN GEWISSES MUSTE HABEN MUSS 
//ENTSPRICHT SIE NICHT DIESEM WIRD EINE FEHLERMELDUNG GEDROPPT


//BEIM PASSWORT IST ES SO DASS ES EINE GEWISSE ANZAHL AN ZEICHEN HABEN MUSS 
//ENTSPRICHT SIE NICHT DIESEM WIRD EINE FEHLERMELDUNG GEDROPPT