// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6PsytyyTH6rilsvr5TsujYDZqfPejJRE',
    appId: '1:690955757902:android:b4d73de34343050345961f',
    messagingSenderId: '690955757902',
    projectId: 'mainapprp',
    storageBucket: 'mainapprp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Rejf0NNTA1Cwgejg_gqLuSbU7-7nxpU',
    appId: '1:690955757902:ios:19abb2ab6253e9e045961f',
    messagingSenderId: '690955757902',
    projectId: 'mainapprp',
    storageBucket: 'mainapprp.appspot.com',
    androidClientId: '690955757902-r40094onskutc9kc32ou2hs8o0d2urs8.apps.googleusercontent.com',
    iosClientId: '690955757902-7veec69q5ucrfamr6ngk53inep9uav6f.apps.googleusercontent.com',
    iosBundleId: 'com.main.riverpodversion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9Rejf0NNTA1Cwgejg_gqLuSbU7-7nxpU',
    appId: '1:690955757902:ios:b2fb7b9777e8aed745961f',
    messagingSenderId: '690955757902',
    projectId: 'mainapprp',
    storageBucket: 'mainapprp.appspot.com',
    androidClientId: '690955757902-r40094onskutc9kc32ou2hs8o0d2urs8.apps.googleusercontent.com',
    iosClientId: '690955757902-rfpu1p1k37thlh3rk7qqp8kpo9h3ukib.apps.googleusercontent.com',
    iosBundleId: 'com.example.appriverpodversion.appRiverpodVersion',
  );
}
